### E-commerce Dataset Cleaning:

In [2]:
import pandas as pd
df = pd.read_csv(r'c:\Users\ASUS\Downloads\archive (3).zip')

In [4]:
df.head(5)                                                                                            #check the dataset

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend
0,8b460852-7c64-46fa-998b-b0976879d082,Customer_65,Product_224,2024-10-06,134,0.14,305.54,11,65,0.17,Electronics,Europe,0.0180,0.55,9.90
1,418612e7-8744-4ba3-bb0c-105b47e2a968,Customer_1910,Product_584,2024-10-29,109,0.30,1102.19,15,201,0.07,Home Appliances,Asia,0.1589,0.40,63.56
2,5bc3b98f-cb0c-4b12-947c-df8bbb35a73e,Customer_2306,Product_374,2024-04-04,116,0.04,471.29,16,199,0.08,Toys,Asia,0.0596,1.50,89.40
3,28fb67c8-e8c0-447a-841c-f760730de0eb,Customer_17206,Product_220,2024-08-25,125,0.20,980.26,12,355,0.03,Clothing,Europe,0.0444,0.44,19.54
4,8bee087a-a8a9-45bb-89d7-04d1710f1b00,Customer_16033,Product_358,2024-05-05,132,0.07,803.76,44,355,0.12,Books,North America,0.1270,0.53,67.31

In [5]:
df.info()                                                                            #deeply cheked with dtypes and non-null-count

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    100000 non-null  str
 1   Customer_ID       100000 non-null  str
 2   Product_ID        100000 non-null  str
 3   Transaction_Date  100000 non-null  str
 4   Units_Sold        100000 non-null  int64
 5   Discount_Applied  100000 non-null  float64
 6   Revenue           100000 non-null  float64
 7   Clicks            100000 non-null  int64
 8   Impressions       100000 non-null  int64
 9   Conversion_Rate   100000 non-null  float64
 10  Category          100000 non-null  str
 11  Region            100000 non-null  str
 12  Ad_CTR            100000 non-null  float64
 13  Ad_CPC            100000 non-null  float64
 14  Ad_Spend          100000 non-null  float64
dtypes: float64(6), int64(3), str(6)
memory usage: 11.4 MB

In [6]:
df.shape

(100000, 15)

In [7]:
df.isnull().sum()                                                                                           #toal null values

Transaction_ID      0
Customer_ID         0
Product_ID          0
Transaction_Date    0
Units_Sold          0
Discount_Applied    0
Revenue             0
Clicks              0
Impressions         0
Conversion_Rate     0
Category            0
Region              0
Ad_CTR              0
Ad_CPC              0
Ad_Spend            0
dtype: int64

In [8]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])                                   #changed it datetime dtypes

In [9]:
df['Transaction_Date'].dtype

dtype('<M8[us]')

In [11]:
df.dtypes

Transaction_ID                 str
Customer_ID                    str
Product_ID                     str
Transaction_Date    datetime64[us]
Units_Sold                   int64
Discount_Applied           float64
Revenue                    float64
Clicks                       int64
Impressions                  int64
Conversion_Rate            float64
Category                       str
Region                         str
Ad_CTR                     float64
Ad_CPC                     float64
Ad_Spend                   float64
dtype: object

In [12]:
df.duplicated().sum()                                                                                 #checked Duplicated values

np.int64(0)

In [13]:
df.sample(5)

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend
42430,56e1541d-6d3c-486d-8a6f-27e8d06dfeec,Customer_17511,Product_509,2024-08-11,88,0.15,331.31,0,267,0.00,Electronics,Europe,0.1030,1.81,186.43
50655,675ba7b0-1cb2-4a1e-8514-6dd30bb75ac2,Customer_6642,Product_338,2023-12-12,84,0.19,103.71,49,109,0.45,Toys,Europe,0.1820,1.80,327.60
446,6c7c2aec-016d-493e-bb66-c8cb83332d3d,Customer_17313,Product_962,2024-10-11,179,0.02,472.69,18,388,0.05,Electronics,Europe,0.1460,0.31,45.26
89542,9c1ff5e3-86db-4d97-9f3d-0a69c650ddfd,Customer_880,Product_579,2024-06-08,99,0.17,371.30,20,410,0.05,Home Appliances,Asia,0.1247,0.49,61.10
6364,006bac07-c260-4fbf-a4f0-ace1399e03ab,Customer_12369,Product_544,2024-08-10,57,0.28,294.12,30,68,0.44,Books,Europe,0.1641,1.74,285.53

In [14]:
df['Product_ID'] = df['Product_ID'].str.replace('Product_' , '' , regex=False);                               #Extract number-id

In [15]:
df['Customer_ID'] = df['Customer_ID'].str.replace('Customer_' ,'' , regex=False)

In [16]:
df.tail(5)

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend
99995,90320769-c92d-4142-b112-4bac46d44007,2613,472,2024-04-21,179,0.11,255.11,41,428,0.10,Electronics,Europe,0.1073,1.48,158.80
99996,e91a3cfa-bd5b-475a-825d-6efe939ff974,19127,787,2024-09-17,178,0.12,1302.60,6,363,0.02,Books,North America,0.1164,0.36,41.90
99997,b0e10e62-e7c4-4092-876a-12abc9ebe3e8,4685,745,2024-10-23,212,0.26,491.36,5,419,0.01,Electronics,North America,0.1235,0.20,24.70
99998,97980811-e107-4369-888c-31cd8763471f,16377,39,2024-01-03,180,0.09,598.91,41,12,3.42,Electronics,Europe,0.1566,0.96,150.34
99999,52f15362-a573-4060-8f70-462f82adda92,14281,223,2024-07-12,157,0.20,208.27,34,334,0.10,Toys,Asia,0.0926,0.61,56.49

In [17]:
df[['Customer_ID' , 'Product_ID']] = df[['Customer_ID', 'Product_ID']].astype(int)                         #changed dtypes as int

In [18]:
df['Transaction_Year'] = df['Transaction_Date'].dt.year

In [19]:
df['Transaction_Months'] = df['Transaction_Date'].dt.month_name()                                       #Add new month_name column

In [20]:
df['Ad_CTR'] = round(df['Ad_CTR'], 2)

In [21]:
df.head(5)

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend,Transaction_Year,Transaction_Months
0,8b460852-7c64-46fa-998b-b0976879d082,65,224,2024-10-06,134,0.14,305.54,11,65,0.17,Electronics,Europe,0.02,0.55,9.90,2024,October
1,418612e7-8744-4ba3-bb0c-105b47e2a968,1910,584,2024-10-29,109,0.30,1102.19,15,201,0.07,Home Appliances,Asia,0.16,0.40,63.56,2024,October
2,5bc3b98f-cb0c-4b12-947c-df8bbb35a73e,2306,374,2024-04-04,116,0.04,471.29,16,199,0.08,Toys,Asia,0.06,1.50,89.40,2024,April
3,28fb67c8-e8c0-447a-841c-f760730de0eb,17206,220,2024-08-25,125,0.20,980.26,12,355,0.03,Clothing,Europe,0.04,0.44,19.54,2024,August
4,8bee087a-a8a9-45bb-89d7-04d1710f1b00,16033,358,2024-05-05,132,0.07,803.76,44,355,0.12,Books,North America,0.13,0.53,67.31,2024,May

In [22]:
df['Category'].unique()

<StringArray>
['Electronics', 'Home Appliances', 'Toys', 'Clothing', 'Books']
Length: 5, dtype: str

In [23]:
df['Region'].unique()

<StringArray>
['Europe', 'Asia', 'North America']
Length: 3, dtype: str

In [25]:
df.sample(5)

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend,Transaction_Year,Transaction_Months
28084,a0f60228-6691-4920-92d7-e766b6979ec1,13402,446,2024-10-28,80,0.09,288.35,7,157,0.04,Toys,North America,0.16,0.73,115.27,2024,October
16024,d7a70a08-dcbf-466f-b651-39541d8fa50b,18743,695,2024-09-04,142,0.02,1352.20,32,190,0.17,Home Appliances,Asia,0.19,0.54,103.46,2024,September
3189,b1d3ca1a-a55c-447c-8340-fc4b7629e018,17156,726,2024-11-02,79,0.30,106.97,8,242,0.03,Clothing,Europe,0.16,0.68,108.32,2024,November
85099,554511df-559a-4c10-bc4f-5e45371df3b4,10639,752,2024-05-29,170,0.22,289.57,2,412,0.00,Home Appliances,Europe,0.12,1.59,183.49,2024,May
83262,d55c3057-e15c-43a9-89fa-5205c9922695,11868,527,2023-12-09,67,0.25,109.02,3,352,0.01,Electronics,Asia,0.10,0.93,95.88,2023,December

In [26]:
df.describe(include='all')

,Transaction_ID,Customer_ID,Product_ID,Transaction_Date,Units_Sold,Discount_Applied,Revenue,Clicks,Impressions,Conversion_Rate,Category,Region,Ad_CTR,Ad_CPC,Ad_Spend,Transaction_Year,Transaction_Months
count,100000,100000.000000,100000.000000,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000
unique,100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,3,NaN,NaN,NaN,NaN,12
top,8b460852-7c64-46fa-998b-b0976879d082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronics,Asia,NaN,NaN,NaN,NaN,October
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21533,33472,NaN,NaN,NaN,NaN,8641
mean,NaN,10026.338760,500.073550,2024-06-06 21:02:49.343999,128.328580,0.149871,553.110811,24.539170,254.539060,0.198138,NaN,NaN,0.105001,1.051250,110.477240,2023.931860,NaN
min,NaN,1.000000,1.000000,2023-12-07 00:00:00,51.000000,0.000000,7.650000,0.000000,10.000000,0.000000,NaN,NaN,0.010000,0.100000,1.050000,2023.000000,NaN
25%,NaN,5026.000000,250.000000,2024-03-07 00:00:00,84.000000,0.070000,221.260000,12.000000,132.000000,0.050000,NaN,NaN,0.060000,0.580000,38.610000,2024.000000,NaN
50%,NaN,10035.000000,500.000000,2024-06-07 00:00:00,127.000000,0.150000,428.155000,25.000000,254.000000,0.100000,NaN,NaN,0.110000,1.050000,87.240000,2024.000000,NaN
75%,NaN,15025.000000,750.000000,2024-09-07 00:00:00,166.000000,0.220000,805.865000,37.000000,377.000000,0.190000,NaN,NaN,0.150000,1.530000,164.220000,2024.000000,NaN
max,NaN,20000.000000,1000.000000,2024-12-06 00:00:00,716.000000,0.300000,5704.180000,49.000000,499.000000,4.900000,NaN,NaN,0.200000,2.000000,399.600000,2024.000000,NaN
std,NaN,5781.473634,288.887286,NaN,49.679873,0.086692,428.366294,14.412477,141.466606,0.361187,NaN,NaN,0.054959,0.549252,87.015846,0.251987,NaN

In [30]:
df.to_csv('Cleaned_Sales_Marketing.csv' , index=False)

### Done